server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locate: en
  datasource:
    url: jdbc:mysql://localhost:3306/nts?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: mJSJRyoLHtQHu2pRvHxFa/LkeZWpTwzUlps0Wh1FzZ8=